version: '3.7'

services:
  car-insurance-app:
    container_name: car-insurance-app
    build:
      context: car-insurance-app
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - car-insurance-services

  car-insurance-services:
    container_name: car-insurance-services
    build:
      context: car-insurance-services
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
  
  # Database Service (Mysql)
  db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    restart: on-failure
    environment:
      MYSQL_DATABASE: car_insurance
      MYSQL_ROOT_PASSWORD: car_insurance
